var mxxArr=[
	{
		id:1,//题号
		question:{
			type:'text',
			ques:'feed是指？'
		},//问题描述
		choice:{
			type:'img',
			result:['1.jpg','2.jpg','3.jpg','4.jpg']
		},
		answer:1
	},
	{
		id:2,//题号
		question:{
			type:'img',
			ques:'下面这张图对应下面哪个单词',
			img:'1.jpg'
		},//问题描述
		choice:{
			type:'html',
			result:['worry','green','grow','feed']
		},
		answer:3
	},
	{
		id:3,//题号
		question:{
			type:'text',
			ques:'pick是指？'
		},//问题描述
		choice:{
			type:'img',
			result:['1.jpg','2.jpg','3.jpg','4.jpg']
		},
		answer:2
	},
	{
		id:4,//题号
		question:{
			type:'img',
			ques:'下面这张图对应下面哪个单词',
			img:'1.jpg'
		},//问题描述
		choice:{
			type:'html',
			result:['question','worry','pick','milk']
		},
		answer:4
	},
	{
		id:5,//题号
		question:{
			type:'img',
			ques:'下面这张图对应下面哪个单词',
			img:'1.jpg'
		},//问题描述
		choice:{
			type:'html',
			result:['Classroom','worry','School','Museum']
		},
		answer:4
	},
	{
		id:6,//题号
		question:{
			type:'text',
			ques:'fire station是指？'
		},//问题描述
		choice:{
			type:'img',
			result:['1.jpg','2.jpg','3.jpg','4.jpg']
		},
		answer:3
	},
	{
		id:7,//题号
		question:{
			type:'img',
			ques:'下面这张图对应下面哪个单词',
			img:'1.jpg'
		},//问题描述
		choice:{
			type:'html',
			result:['robot','guide','doctor','teacher']
		},
		answer:1
	},
	{
		id:8,//题号
		question:{
			type:'text',
			ques:'guide是指？'
		},//问题描述
		choice:{
			type:'img',
			result:['1.jpg','2.jpg','3.jpg','4.jpg']
		},
		answer:2
	},
	{
		id:9,//题号
		question:{
			type:'text',
			ques:'restaurant是指？'
		},//问题描述
		choice:{
			type:'img',
			result:['1.jpg','2.jpg','3.jpg','4.jpg']
		},
		answer:4
	},
	{
		id:10,//题号
		question:{
			type:'img',
			ques:'下面这张图对应下面哪个单词',
			img:'1.jpg'
		},//问题描述
		choice:{
			type:'html',
			result:['hospital','museum','restaurant','kitchen']
		},
		answer:1
	},
	{
		id:11,//题号
		question:{
			type:'text',
			ques:'kitchen是指？'
		},//问题描述
		choice:{
			type:'img',
			result:['1.jpg','2.jpg','3.jpg','4.jpg']
		},
		answer:2
	},
	{
		id:12,//题号
		question:{
			type:'text',
			ques:'actor是指？'
		},//问题描述
		choice:{
			type:'html',
			result:['老师','护士','医生','演员']
		},
		answer:4
	},
	{
		id:13,//题号
		question:{
			type:'img',
			ques:'下面这张图对应下面哪个单词',
			img:'1.jpg'
		},//问题描述
		choice:{
			type:'html',
			result:['visitor','artist','guide','actor']
		},
		answer:1
	},
	{
		id:14,//题号
		question:{
			type:'text',
			ques:'gift是指？'
		},//问题描述
		choice:{
			type:'img',
			result:['1.jpg','2.jpg','3.jpg','4.jpg']
		},
		answer:2
	},
	{
		id:15,//题号
		question:{
			type:'text',
			ques:'person是指？'
		},//问题描述
		choice:{
			type:'img',
			result:['1.jpg','2.jpg','3.jpg','4.jpg']
		},
		answer:4
	},
]
